version: "3"
services:
    backend:
        image: localhost/sschat-server
        # ports: # don't allow access to the outside world
        #     - "8000:8000"
        environment:
            - SECRET_KEY=${SECRET_KEY}
        # volumes:
            # - "db.sqlite3:/app/sschat/db.sqlite3"
    frontend:
        image: localhost/sschat-client
        ports:
            - "8080:443"
        environment:
            - PROXY_API=http://backend:8000
        # volumes:
        #     - ./logs/:/var/log/nginx/
            # - ./clients/env/certs/:/etc/nginx/certs/
        depends_on:
            - backend