version: "3"
services:
    backend:
        image: localhost/sschat-server
        environment:
            - SECRET_KEY=${SECRET_KEY}
        # volumes:
        #     - ./database:/app/database/
    frontend:
        image: localhost/sschat-client
        ports:
            - "8080:443"
        environment:
            - PROXY_API=http://backend:8000
        # volumes:
            # - logs/:/var/log/nginx/
            # - ./clients/env/certs/:/etc/nginx/certs/
        depends_on:
            - backend