version: "3"
services:
    backend:
        image: localhost/sschat-server
        ports:
            - "8000:8000"
        environement:
            - SERCRET_KEY=${SECRET_KEY}
    frontend:
        image: localhost/sschat-client
        ports:
            - "8080:443"
        environement:
            - proxy_api=http://backend:8000
        # volumes:
        #     - ./clients/env/certs/:/etc/nginx/certs
        depends_on:
            - backend