version: "3.3"
services:
    backend:
        image: localhost/sschat-server
        environment:
            - SECRET_KEY=${SECRET_KEY}
        build:
            context: ./server
            dockerfile: ./Dockerfile
        # volumes:
        #     - ./database:/app/database/
    frontend:
        image: localhost/sschat-client
        ports:
            - "8080:443"
        environment:
            - PROXY_API=http://backend:8000
            - API_HOST=https://localhost:8080/api
        build:
            context: ./client
            dockerfile: ./Dockerfile
        volumes:
            - type: bind
              source: ./client/env/certs
              target: /etc/nginx/certs
              read_only: true
        depends_on:
            - backend