# Generated by Django 4.0.4 on 2022-05-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_remove_friendships_friend_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='public_pgp_key',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='msg.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='msg.profile')),
            ],
        ),
    ]
